name: Deploy Avalonia Browser App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.203'  # Ajustez selon votre version
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build browser project
      run: dotnet publish MinecraftWerewolf.Browser/MinecraftWerewolf.Browser.csproj -c Release -o ./dist
      # Remplacez par le chemin exact de votre projet browser
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './MinecraftWerewolf.Browser/bin/Release/net8.0-browser/publish/wwwroot' 
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
